### ISSUE TITLE
Warning: pattern.indexOf is not a function

### ISSUE THREAD

**Issue by F1LT3R** [LotusTM/grunt-sitemap-xml#1]
When trying to use this grunt task I receive the following error:

```shell
Running "sitemap_xml:files" (sitemap_xml) task
Warning: pattern.indexOf is not a function Use --force to continue.

Aborted due to warnings.
```

Here is the my grunt config for `sitemap_xml`:

```javascript
     sitemap_xml: {
      files: [
        {
          cwd: 'dest',
          src: 'dest/**/*.html',
          dest: 'dest/sitemap.xml'
        }
      ]
    },
```

Any ideas what could be causing this? The error is a bit ambiguous, but I am assuming this means that no files were found? If that is the case, perhaps the error message should reflect this?

**Comment by F1LT3R** [comment]
With `grunt --stack` I found that the error came from `tasks/sitemap_xml.js:48`:

```coffeescript
    // Iterate over all specified file groups
    this.files.forEach(file => {
```

Not finding an index in `files` made me realize I a target was needed:

So I tried, this, which worked:

```javascript
     sitemap_xml: {
       mytarget: {
          files: [
          {
            cwd: 'dest',
            src: 'dest/**/*.html',
            dest: 'dest/sitemap.xml'
          }
        ],
      },
    },
```

**Comment by F1LT3R** [comment]
Maybe it's worth updating the [usage example](https://github.com/LotusTM/grunt-sitemap-xml#usage-example) in the README?

Does that example really work without a target?

```javascript
grunt.initConfig({
  sitemap_xml: {
      files: [
        {
          cwd: 'app/build',
          src: '{,**/}*.html',
          dest: 'app/build/sitemap.xml'
        }
      ]
  },
});
```

**Comment by mrhyde** [comment]
Hi Alistar, I'm sorry to see you running in such an inconvenient situation. I will take a closer look at this particular case and update tests to cover such situations.

**Comment by ArmorDarks** [comment]
@F1LT3R thanks for report and sorry for inconvenience.

`grunt-sitemap-xml` is Grunt multitask, and according to Grunt requirements for multitasks specifying of at least single target is mandatory.

This is definitely an error in our documentation, we will fix it asap.
